---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valheim.fullname" . }}-lists
data:
  {{- range $path,$bytes := .Files.Glob "lists/**" }}
  {{ $path | base -}}: |
{{- $.Files.Get $path | nindent 6 }}
  {{- end }}
